### ISSUE TITLE
[request] UPTIME command support

### ISSUE THREAD

**Issue by bigretromike** [fpob/yumemi#2]
When you hold connection for longer time (ex. 30minuts) wiki recommand this:

> UPTIME: Retrieve Server Uptime
> Command String:
>     UPTIME
> Possible Replies:
>     208 UPTIME
>     {int4 udpserver uptime in milliseconds}
> Info: This command is the preferred way to check that the session is OK.

Would be super to have this for those how loop yumemi

**Comment by fpob** [comment]
You mean add method that will use this command to check if the session is valid? For now you can use `client.call('UPTIME').code == 208` but I agree that something like `client.check_session()` would be better.

**Comment by bigretromike** [comment]
You are right, one could `call('UPTIME')` but same goes for `ping` which have its own command. Uptime command is prefered way to tell UDP server that client is still connected and waiting for data to pass - when you open socket and don't want to disconnect because you are making big hash collection ready to be send.  because acorgind to wiki you should have steady connection when you know there is data to be send in next 15minuts or so, while you wait you should call `uptime` as a way to say to server that 'hey, im still here, dont close connection'. But using `call` is a good way to workaround this 👍 thanks

**Comment by fpob** [comment]
Added in 7ecc46477cad5527b9b732ec8e5447286481d42f, `v1.2`

**Comment by bigretromike** [comment]
Thanks a lot ! :+1:
